export function configFiles(c) {
  const a = c.apedDir;
  const o = c.outputDir;
  const ts = c.ticketSystem || 'none';
  const gp = c.gitProvider || 'github';
  const ver = c.cliVersion || '0.0.0';
  return [
    {
      path: `${a}/config.yaml`,
      content: `# APED Project Configuration
project_name: ${c.projectName}
user_name: ${c.authorName}
communication_language: ${c.communicationLang}
document_output_language: ${c.documentLang}
aped_path: ${a}
output_path: ${o}
aped_version: ${ver}

# Integrations
ticket_system: ${ts}
git_provider: ${gp}
`,
    },
    {
      path: `${o}/state.yaml`,
      content: `# APED Pipeline State
# Phases: none → analyze → prd → ux → architecture → sprint
# "sprint" is the final phase — covers story/dev/review cycle
pipeline:
  current_phase: "none"
  phases: {}

# Sprint state (generated by aped-epics, consumed by aped-story/aped-dev/aped-review/aped-sprint)
#
# parallel_limit — max stories dispatched concurrently (each in its own worktree)
# review_limit   — max reviews running concurrently (spec-teams are token-heavy)
# active_epic    — number of the epic currently in sprint (only one at a time)
#
# Per-story status: pending → ready-for-dev → in-progress → review-queued → review → done
# Per-story fields:
#   ticket:       external ticket ID (Linear/Jira/GitHub/GitLab), optional
#   worktree:     path to the git worktree hosting this story, set by /aped-sprint
#   depends_on:   list of story keys that must be "done" before this one can dispatch
#   started_at:   ISO8601 timestamp set when status flips to in-progress
sprint:
  project: ""
  active_epic: null
  parallel_limit: 3
  review_limit: 2
  stories: {}
`,
    },
    {
      path: `${a}/templates/product-brief.md`,
      content: `# Product Brief: {{project_name}}

## Executive Summary

<!-- 2-3 sentences: what we're building and why it matters -->

## Core Vision

### Problem Statement

<!-- What specific problem exists today? -->

### Problem Impact

<!-- Who is affected and how? Quantify where possible. -->

### Proposed Solution

<!-- High-level description of the solution approach -->

### Key Differentiators

<!-- What makes this different from existing solutions? -->

## Target Users

### Primary Users

<!-- Who are the main users? Demographics, behaviors, technical level -->

### Secondary Users

<!-- Other stakeholders who interact with the product -->

### User Journey

<!-- Key touchpoints from discovery to daily usage -->

## Success Metrics

### Business Objectives

<!-- What business outcomes define success? -->

### KPIs

<!-- Measurable indicators with targets and timeframes -->

## MVP Scope

### Core Features

<!-- Minimum feature set for first viable release -->

### Out of Scope

<!-- Explicitly excluded from MVP -->

### Success Criteria

<!-- How we know MVP succeeded -->

### Future Vision

<!-- Post-MVP direction and growth areas -->
`,
    },
    {
      path: `${a}/templates/prd.md`,
      content: `# Product Requirements Document — {{project_name}}

**Author:** {{user_name}}
**Date:** {{date}}

## Executive Summary

## Success Criteria

### User Outcomes

### Business Outcomes

### Technical Outcomes

### Measurable Outcomes

## Product Scope

### MVP (Phase 1)

### Growth (Phase 2)

### Vision (Phase 3)

## User Journeys

## Domain Requirements

<!-- Conditional: only if domain-complexity.csv flags high/medium complexity -->

## Functional Requirements

<!-- Format: FR#: [Actor] can [capability] [context/constraint] -->
<!-- Target: 10-80 FRs -->

## Non-Functional Requirements

### Performance

### Security

### Scalability

### Accessibility

### Integration
`,
    },
    {
      path: `${a}/templates/epics.md`,
      content: `# Epics & Stories — {{project_name}}

**Generated:** {{date}}
**Source PRD:** {{prd_path}}

## Requirements Inventory

### Functional Requirements

### Non-Functional Requirements

### Additional Requirements

## FR Coverage Map

<!-- Every FR mapped to exactly one epic. Format: FR# -> Epic N -->

## Epics

### Epic 1: {{epic_title}}

**Goal:** {{user-value-focused goal}}

#### Story 1.1: {{story_title}}

**Depends on:** {{comma-separated story keys, e.g. "1-2, 1-3", or "none"}}

**As a** {{role}}, **I want** {{capability}}, **so that** {{benefit}}.

**Acceptance Criteria:**
- **Given** {{context}}, **When** {{action}}, **Then** {{outcome}}

**Tasks:**
- [ ] {{task description}} [AC: {{ac_ref}}]

**Dev Notes:**
- Architecture: {{relevant patterns}}
- Files: {{files to create/modify}}
- Testing: {{test approach}}
`,
    },
    {
      path: `${a}/templates/story.md`,
      content: `# Story: {{story_key}} — {{story_title}}

**Epic:** {{epic_title}}
**Status:** {{status}}

## User Story

**As a** {{role}}, **I want** {{capability}}, **so that** {{benefit}}.

## Acceptance Criteria

- **Given** {{context}}, **When** {{action}}, **Then** {{outcome}}

## Tasks

- [ ] {{task description}} [AC: {{ac_ref}}]

## Dev Notes

- **Architecture:** {{relevant architecture decisions and patterns}}
- **Files:** {{files to create or modify}}
- **Testing:** {{test approach and framework}}
- **Dependencies:** {{external libs, APIs, services}}

## Dev Agent Record

- **Model:** {{model used}}
- **Started:** {{timestamp}}
- **Completed:** {{timestamp}}

### Debug Log

### Completion Notes

### File List
`,
    },
    {
      path: `${a}/templates/workmux.yaml.example`,
      content: `# Example .workmux.yaml — copy to your repo root if you use workmux
# (https://github.com/raine/workmux) alongside APED. /aped-sprint detects
# workmux automatically and will use it to spawn tmux windows with Claude
# Code pre-launched per story.
#
# Docs: https://workmux.raine.dev/

# Pane layout inside each worktree window.
#
# We hardcode \`claude --permission-mode bypassPermissions\` instead of the
# generic \`<agent>\` placeholder for two reasons:
#   1. Parallel sprints launch N worktrees at once; stopping to approve
#      every tool call would defeat the whole point of parallelism.
#   2. The project's \`.claude/settings.local.json\` (copied via files.copy
#      below) already captures the allow/deny rules — bypassPermissions
#      trusts that inventory. Keep that settings file honest.
# If you prefer interactive permissions per worktree, swap the command to
# \`claude\` (or \`<agent>\` with \`agent: claude\` in global config).
# Workmux auto-detects built-in agents (claude/gemini/codex/opencode/…) in
# the pane command even with flags, so prompt injection via \`workmux add -p\`
# still works.
panes:
  - command: claude --permission-mode bypassPermissions
    focus: true
  # Uncomment a dev-server pane if you want one automatically:
  # - command: pnpm dev
  #   split: horizontal
  #   size: 30

# Copy these paths into every new worktree.
#
# We copy \`.claude/\` and \`.aped/\` in full on purpose: many APED users
# gitignore them as user-local tooling (the CloudVault setup, for instance,
# ignores both), so a fresh worktree on a feature branch has NEITHER the
# APED skill/hook machinery NOR the Claude settings. Without the copy, the
# worktree's Claude Code session would fail on the very first prompt — the
# UserPromptSubmit hook tries to invoke \`.aped/hooks/guardrail.sh\` and
# misses.
#
# If your project tracks these paths (rare), the copy is a harmless duplicate
# — git's tracked content is already there, workmux copies the same bytes on
# top. No conflict, no divergence concern.
#
# Paths:
#   .env*                       project secrets and per-env configs
#   .mcp.json                   project-scoped Claude Code MCP servers
#                               (Linear, Stripe, etc. — critical for
#                               /aped-story ticket fetches and /aped-dev)
#   .claude/                    commands, skills, settings (including
#                               settings.local.json for permission sharing)
#   .aped/                      full APED pipeline: skills, hooks, scripts,
#                               templates, config.yaml. Includes hooks/
#                               so guardrail.sh / upstream-lock.sh resolve
#                               in the worktree
#
# Globs are supported. Add more entries if your project has extra files
# (e.g., .vscode/settings.json, credentials, local overrides).
files:
  copy:
    - .env*
    - .mcp.json
    - .claude/
    - .aped/
  # Symlink heavy dirs instead of copying — saves disk and install time.
  symlink:
    - node_modules

# Commands run once per worktree right after creation.
post_create:
  - pnpm install --frozen-lockfile || npm install

# Optional: automatic branch naming via LLM when you run \`workmux add -A\`.
# auto_name:
#   cli: claude
`,
    },
    {
      path: `${a}/templates/quick-spec.md`,
      content: `# Quick Spec: {{title}}

**Date:** {{date}}
**Author:** {{user_name}}
**Type:** {{fix|feature|refactor}}
**Status:** draft | in-progress | done | abandoned

## What

<!-- 1-2 sentences: what needs to change -->

## Why

<!-- 1 sentence: why this change matters now -->

## Acceptance Criteria

- [ ] {{criterion}}

## Files to Change

- {{file_path}} — {{what to change}}

## Test Plan

- {{test description}}

## Result

<!-- Filled after implementation -->
<!-- Files changed, tests added, outcome -->
`,
    },
  ];
}
