export function configFiles(c) {
  const a = c.apedDir;
  const o = c.outputDir;
  const ts = c.ticketSystem || 'none';
  const gp = c.gitProvider || 'github';
  const ver = c.cliVersion || '0.0.0';
  return [
    {
      path: `${a}/config.yaml`,
      content: `# APED Project Configuration
project_name: ${c.projectName}
user_name: ${c.authorName}
communication_language: ${c.communicationLang}
document_output_language: ${c.documentLang}
aped_path: ${a}
output_path: ${o}
aped_version: ${ver}

# Integrations
ticket_system: ${ts}
git_provider: ${gp}
`,
    },
    {
      path: `${o}/state.yaml`,
      content: `# APED Pipeline State
pipeline:
  current_phase: "none"
  phases: {}

# Sprint state (generated by aped-epics, consumed by aped-dev and aped-review)
sprint:
  project: ""
  stories: {}
`,
    },
    {
      path: `${a}/templates/product-brief.md`,
      content: `# Product Brief: {{project_name}}

## Executive Summary

<!-- 2-3 sentences: what we're building and why it matters -->

## Core Vision

### Problem Statement

<!-- What specific problem exists today? -->

### Problem Impact

<!-- Who is affected and how? Quantify where possible. -->

### Proposed Solution

<!-- High-level description of the solution approach -->

### Key Differentiators

<!-- What makes this different from existing solutions? -->

## Target Users

### Primary Users

<!-- Who are the main users? Demographics, behaviors, technical level -->

### Secondary Users

<!-- Other stakeholders who interact with the product -->

### User Journey

<!-- Key touchpoints from discovery to daily usage -->

## Success Metrics

### Business Objectives

<!-- What business outcomes define success? -->

### KPIs

<!-- Measurable indicators with targets and timeframes -->

## MVP Scope

### Core Features

<!-- Minimum feature set for first viable release -->

### Out of Scope

<!-- Explicitly excluded from MVP -->

### Success Criteria

<!-- How we know MVP succeeded -->

### Future Vision

<!-- Post-MVP direction and growth areas -->
`,
    },
    {
      path: `${a}/templates/prd.md`,
      content: `# Product Requirements Document — {{project_name}}

**Author:** {{user_name}}
**Date:** {{date}}

## Executive Summary

## Success Criteria

### User Outcomes

### Business Outcomes

### Technical Outcomes

### Measurable Outcomes

## Product Scope

### MVP (Phase 1)

### Growth (Phase 2)

### Vision (Phase 3)

## User Journeys

## Domain Requirements

<!-- Conditional: only if domain-complexity.csv flags high/medium complexity -->

## Functional Requirements

<!-- Format: FR#: [Actor] can [capability] [context/constraint] -->
<!-- Target: 10-80 FRs -->

## Non-Functional Requirements

### Performance

### Security

### Scalability

### Accessibility

### Integration
`,
    },
    {
      path: `${a}/templates/epics.md`,
      content: `# Epics & Stories — {{project_name}}

**Generated:** {{date}}
**Source PRD:** {{prd_path}}

## Requirements Inventory

### Functional Requirements

### Non-Functional Requirements

### Additional Requirements

## FR Coverage Map

<!-- Every FR mapped to exactly one epic. Format: FR# -> Epic N -->

## Epics

### Epic 1: {{epic_title}}

**Goal:** {{user-value-focused goal}}

#### Story 1.1: {{story_title}}

**As a** {{role}}, **I want** {{capability}}, **so that** {{benefit}}.

**Acceptance Criteria:**
- **Given** {{context}}, **When** {{action}}, **Then** {{outcome}}

**Tasks:**
- [ ] {{task description}} [AC: {{ac_ref}}]

**Dev Notes:**
- Architecture: {{relevant patterns}}
- Files: {{files to create/modify}}
- Testing: {{test approach}}
`,
    },
    {
      path: `${a}/templates/story.md`,
      content: `# Story: {{story_key}} — {{story_title}}

**Epic:** {{epic_title}}
**Status:** {{status}}

## User Story

**As a** {{role}}, **I want** {{capability}}, **so that** {{benefit}}.

## Acceptance Criteria

- **Given** {{context}}, **When** {{action}}, **Then** {{outcome}}

## Tasks

- [ ] {{task description}} [AC: {{ac_ref}}]

## Dev Notes

- **Architecture:** {{relevant architecture decisions and patterns}}
- **Files:** {{files to create or modify}}
- **Testing:** {{test approach and framework}}
- **Dependencies:** {{external libs, APIs, services}}

## Dev Agent Record

- **Model:** {{model used}}
- **Started:** {{timestamp}}
- **Completed:** {{timestamp}}

### Debug Log

### Completion Notes

### File List
`,
    },
    {
      path: `${a}/templates/quick-spec.md`,
      content: `# Quick Spec: {{title}}

**Date:** {{date}}
**Author:** {{user_name}}
**Type:** {{fix|feature|refactor}}
**Status:** draft | in-progress | done | abandoned

## What

<!-- 1-2 sentences: what needs to change -->

## Why

<!-- 1 sentence: why this change matters now -->

## Acceptance Criteria

- [ ] {{criterion}}

## Files to Change

- {{file_path}} — {{what to change}}

## Test Plan

- {{test description}}

## Result

<!-- Filled after implementation -->
<!-- Files changed, tests added, outcome -->
`,
    },
  ];
}
