export function configFiles(c) {
  const a = c.apedDir;
  const o = c.outputDir;
  const ts = c.ticketSystem || 'none';
  const gp = c.gitProvider || 'github';
  const ver = c.cliVersion || '0.0.0';
  return [
    {
      path: `${a}/config.yaml`,
      content: `# APED Project Configuration
project_name: ${c.projectName}
user_name: ${c.authorName}
communication_language: ${c.communicationLang}
document_output_language: ${c.documentLang}
aped_path: ${a}
output_path: ${o}
aped_version: ${ver}

# Integrations
ticket_system: ${ts}
git_provider: ${gp}
`,
    },
    {
      path: `${o}/state.yaml`,
      content: `# APED Pipeline State
pipeline:
  current_phase: "none"
  phases: {}

# Sprint state (generated by aped-epics, consumed by aped-dev and aped-review)
sprint:
  project: ""
  stories: {}
`,
    },
    {
      path: `${a}/templates/product-brief.md`,
      content: `# Product Brief: {{project_name}}

## Executive Summary

<!-- 2-3 sentences: what we're building and why it matters -->

## Core Vision

### Problem Statement

<!-- What specific problem exists today? -->

### Problem Impact

<!-- Who is affected and how? Quantify where possible. -->

### Proposed Solution

<!-- High-level description of the solution approach -->

### Key Differentiators

<!-- What makes this different from existing solutions? -->

## Target Users

### Primary Users

<!-- Who are the main users? Demographics, behaviors, technical level -->

### Secondary Users

<!-- Other stakeholders who interact with the product -->

### User Journey

<!-- Key touchpoints from discovery to daily usage -->

## Success Metrics

### Business Objectives

<!-- What business outcomes define success? -->

### KPIs

<!-- Measurable indicators with targets and timeframes -->

## MVP Scope

### Core Features

<!-- Minimum feature set for first viable release -->

### Out of Scope

<!-- Explicitly excluded from MVP -->

### Success Criteria

<!-- How we know MVP succeeded -->

### Future Vision

<!-- Post-MVP direction and growth areas -->
`,
    },
    {
      path: `${a}/templates/prd.md`,
      content: `# Product Requirements Document — {{project_name}}

**Author:** {{user_name}}
**Date:** {{date}}

## Executive Summary

## Success Criteria

### User Outcomes

### Business Outcomes

### Technical Outcomes

### Measurable Outcomes

## Product Scope

### MVP (Phase 1)

### Growth (Phase 2)

### Vision (Phase 3)

## User Journeys

## Domain Requirements

<!-- Conditional: only if domain-complexity.csv flags high/medium complexity -->

## Functional Requirements

<!-- Format: FR#: [Actor] can [capability] [context/constraint] -->
<!-- Target: 10-80 FRs -->

## Non-Functional Requirements

### Performance

### Security

### Scalability

### Accessibility

### Integration
`,
    },
    {
      path: `${a}/templates/epics.md`,
      content: `# Epics & Stories — {{project_name}}

**Generated:** {{date}}
**Source PRD:** {{prd_path}}

## Requirements Inventory

### Functional Requirements

### Non-Functional Requirements

### Additional Requirements

## FR Coverage Map

<!-- Every FR mapped to exactly one epic. Format: FR# -> Epic N -->

## Epics

### Epic 1: {{epic_title}}

**Goal:** {{user-value-focused goal}}

#### Story 1.1: {{story_title}}

**As a** {{role}}, **I want** {{capability}}, **so that** {{benefit}}.

**Acceptance Criteria:**
- **Given** {{context}}, **When** {{action}}, **Then** {{outcome}}

**Tasks:**
- [ ] {{task description}} [AC: {{ac_ref}}]

**Dev Notes:**
- Architecture: {{relevant patterns}}
- Files: {{files to create/modify}}
- Testing: {{test approach}}
`,
    },
    {
      path: `${a}/templates/story.md`,
      content: `# Story: {{story_key}} — {{story_title}}

**Epic:** {{epic_title}}
**Status:** {{status}}

## User Story

**As a** {{role}}, **I want** {{capability}}, **so that** {{benefit}}.

## Acceptance Criteria

- **Given** {{context}}, **When** {{action}}, **Then** {{outcome}}

## Tasks

- [ ] {{task description}} [AC: {{ac_ref}}]

## Dev Notes

- **Architecture:** {{relevant architecture decisions and patterns}}
- **Files:** {{files to create or modify}}
- **Testing:** {{test approach and framework}}
- **Dependencies:** {{external libs, APIs, services}}

## Dev Agent Record

- **Model:** {{model used}}
- **Started:** {{timestamp}}
- **Completed:** {{timestamp}}

### Debug Log

### Completion Notes

### File List
`,
    },
    {
      path: `CLAUDE.md`,
      content: `# ${c.projectName}

This project uses the **APED Method** — a disciplined, user-driven dev pipeline.
Every step requires explicit user validation. No phase auto-chains.

Pipeline: \`Analyze → PRD → UX → Architecture → Epics → Story → Dev → Review\`

## Working Rules

### 1. Plan Mode Default
- Enter plan mode for ANY non-trivial task (3+ steps or architectural decisions)
- If something goes sideways, STOP and re-plan immediately — don't keep pushing
- Use plan mode for verification steps, not just building
- Write detailed specs upfront to reduce ambiguity

### 2. Subagent Strategy
- Use subagents liberally to keep main context window clean
- Offload research, exploration, and parallel analysis to subagents
- For complex problems, throw more compute at it via subagents
- One task per subagent for focused execution

### 3. Self-Improvement Loop
- After ANY correction from the user: update \`${o}/lessons.md\` with the pattern
- Write rules for yourself that prevent the same mistake
- Ruthlessly iterate on these lessons until mistake rate drops
- Review lessons at session start

### 4. Verification Before Done
- Never mark a task complete without proving it works
- Diff behavior between main and your changes when relevant
- Ask yourself: "Would a staff engineer approve this?"
- Run tests, check logs, demonstrate correctness

### 5. Demand Elegance (Balanced)
- For non-trivial changes: pause and ask "is there a more elegant way?"
- If a fix feels hacky: "Knowing everything I know now, implement the elegant solution"
- Skip this for simple, obvious fixes — don't over-engineer
- Challenge your own work before presenting it

### 6. Autonomous Bug Fixing
- When given a bug report: just fix it. Don't ask for hand-holding
- Point at logs, errors, failing tests — then resolve them
- Zero context switching required from the user
- Go fix failing CI tests without being told how

## APED-Specific Rules

### 7. Never Auto-Chain Phases
- Each APED skill ends with "Run /aped-X when ready" — STOP there
- Wait for the user to explicitly invoke the next phase
- Even if the next step is obvious, the user controls the pace

### 8. Validate Before Persisting
- \`/aped-analyze\`, \`/aped-prd\`, \`/aped-arch\`, \`/aped-epics\`, \`/aped-story\` all require user approval before writing artifacts
- Never write to \`${o}/\` until the user has explicitly validated the content
- If user requests changes: apply, re-present, wait for new approval

### 9. Story-Driven Dev
- Never code without a story file (use \`/aped-story\` first)
- Never start a story without verifying the story file exists
- Use the epic context cache (\`${o}/epic-{N}-context.md\`) — don't re-read the PRD every time

### 10. Frontend = Visual Verification
- Detect frontend stories (\`.tsx\`, \`.jsx\`, \`.vue\`, \`.svelte\`)
- Use \`mcp__react-grab-mcp__get_element_context\` at each GREEN pass during dev
- React Grab is also a 6th GATE condition for frontend tasks
- In review, frontend stories get a 3rd visual review agent automatically

## Task Management

1. **Plan First**: Use TaskCreate to capture a plan with checkable items
2. **Verify Plan**: Check in with the user before starting implementation
3. **Track Progress**: TaskUpdate as you complete items (in_progress → completed)
4. **Explain Changes**: High-level summary at each milestone
5. **Document Results**: Update story file's Dev Agent Record section
6. **Capture Lessons**: Update \`${o}/lessons.md\` after corrections

## Core Principles

- **Simplicity First** — Make every change as simple as possible. Impact minimal code.
- **No Laziness** — Find root causes. No temporary fixes. Senior developer standards.
- **User Controls Pace** — APED is collaborative, not automated. Wait for explicit approval.
- **Quality > Speed** — Take your time. Validation gates exist for a reason.

## State & Artifacts

- Engine: \`${a}/\` (immutable after install)
- Artifacts: \`${o}/\` (evolves during project)
- State machine: \`${o}/state.yaml\`
- Lessons learned: \`${o}/lessons.md\`

## Slash Commands

| Pipeline | Utility |
|----------|---------|
| \`/aped-analyze\` | \`/aped-status\` |
| \`/aped-prd\` | \`/aped-course\` |
| \`/aped-ux\` | \`/aped-context\` |
| \`/aped-arch\` | \`/aped-qa\` |
| \`/aped-epics\` | \`/aped-quick\` |
| \`/aped-story\` | \`/aped-check\` |
| \`/aped-dev\` | |
| \`/aped-review\` | |
`,
    },
    {
      path: `${o}/lessons.md`,
      content: `# Lessons Learned

This file captures patterns from user corrections so the same mistake isn't made twice.

## Format

Each entry:
- **Date:** YYYY-MM-DD
- **Mistake:** What I did wrong
- **Correction:** What the user told me
- **Rule:** The pattern to apply going forward

## Entries

<!-- Add new entries at the top -->
`,
    },
    {
      path: `${a}/templates/quick-spec.md`,
      content: `# Quick Spec: {{title}}

**Date:** {{date}}
**Author:** {{user_name}}
**Type:** {{fix|feature|refactor}}
**Status:** draft | in-progress | done | abandoned

## What

<!-- 1-2 sentences: what needs to change -->

## Why

<!-- 1 sentence: why this change matters now -->

## Acceptance Criteria

- [ ] {{criterion}}

## Files to Change

- {{file_path}} — {{what to change}}

## Test Plan

- {{test description}}

## Result

<!-- Filled after implementation -->
<!-- Files changed, tests added, outcome -->
`,
    },
  ];
}
