import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, mkdirSync, chmodSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { scripts } from '../src/templates/scripts.js';
import { references } from '../src/templates/references.js';

const APED_DIR = '.aped';
const OUTPUT_DIR = 'aped-output';
const ALL_SCRIPTS = scripts({ apedDir: APED_DIR, outputDir: OUTPUT_DIR });
const ALL_REFS = references({ apedDir: APED_DIR });

function findScript(suffix) {
  const s = ALL_SCRIPTS.find((x) => x.path.endsWith(suffix));
  if (!s) throw new Error(`No script template ending in ${suffix}`);
  return s;
}
function findRef(suffix) {
  const r = ALL_REFS.find((x) => x.path.endsWith(suffix));
  if (!r) throw new Error(`No reference template ending in ${suffix}`);
  return r;
}

function setupSandbox() {
  const root = mkdtempSync(join(tmpdir(), 'aped-epic-ctx-schema-test-'));
  mkdirSync(join(root, APED_DIR, 'scripts', 'lib'), { recursive: true });
  mkdirSync(join(root, APED_DIR, 'data'), { recursive: true });
  mkdirSync(join(root, OUTPUT_DIR, 'epics-context'), { recursive: true });

  const validator = findScript('scripts/validate-epic-context.sh');
  const walker = findScript('scripts/lib/markdown-schema-walk.mjs');
  const schema = findRef('data/epic-context.schema.json');

  writeFileSync(join(root, validator.path), validator.content);
  chmodSync(join(root, validator.path), 0o755);
  writeFileSync(join(root, walker.path), walker.content);
  writeFileSync(join(root, schema.path), schema.content);
  return root;
}

function run(root, target) {
  const r = spawnSync(
    'bash',
    [join(root, APED_DIR, 'scripts', 'validate-epic-context.sh'), join(root, target)],
    { encoding: 'utf8' },
  );
  return { code: r.status ?? -1, stderr: r.stderr ?? '', stdout: r.stdout ?? '' };
}

const CONFORMANT_CACHE = `# Epic 1 — Context Cache

_Generated by aped-story at 2026-05-07T15:00:00Z._

## Scope from PRD

- FRs in this epic: FR1 — Foo, FR2 — Bar
- NFRs that bind: NFR1 — performance

## Architecture references

- Patterns to respect: feature-sliced design
- ADRs in scope: adr/0001-foo.md

## UX references

- Screens: dashboard, settings
- Components: Button, Modal

## Project context (brownfield only)

- Existing patterns the epic must respect: n/a (greenfield)

## Lessons applicable

- (none — first epic)

## Previous stories — outcomes

_(Appended by aped-review at story→done. Empty on first story of the epic.)_

### Story 1-1-foo — done 2026-05-07T16:00:00Z

- Decisions: chose JWT over session
- Files: src/auth.ts
- Contracts: POST /login → { token }
- Deviations: none
`;

let sandbox;
beforeEach(() => { sandbox = setupSandbox(); });
afterEach(() => { rmSync(sandbox, { recursive: true, force: true }); });

describe('validate-epic-context.sh', () => {
  it('exits 0 on a conformant cache (with appended ### Story block)', () => {
    const target = join(OUTPUT_DIR, 'epics-context', 'epic-1-context.md');
    writeFileSync(join(sandbox, target), CONFORMANT_CACHE);
    const r = run(sandbox, target);
    expect(r.code, `stderr: ${r.stderr}`).toBe(0);
    expect(r.stderr).toBe('');
  });

  it('flags missing "Previous stories — outcomes" heading (aped-review breakage)', () => {
    const broken = CONFORMANT_CACHE.replace(/## Previous stories — outcomes[\s\S]*$/, '');
    const target = join(OUTPUT_DIR, 'epics-context', 'epic-1-context.md');
    writeFileSync(join(sandbox, target), broken);
    const r = run(sandbox, target);
    expect(r.code).toBe(1);
    expect(r.stderr).toMatch(/missing required heading 'Previous stories — outcomes'/);
  });

  it('flags an invented top-level heading', () => {
    const broken = CONFORMANT_CACHE.replace(
      '## Lessons applicable',
      '## Risks\n\n- some risk\n\n## Lessons applicable',
    );
    const target = join(OUTPUT_DIR, 'epics-context', 'epic-1-context.md');
    writeFileSync(join(sandbox, target), broken);
    const r = run(sandbox, target);
    expect(r.code).toBe(1);
    expect(r.stderr).toMatch(/invented top-level heading 'Risks'/);
  });

  it('does NOT flag the appended "### Story X — done ISO" block as invented', () => {
    // The cache's repeatable level-3 entries under "Previous stories —
    // outcomes" are intentionally permitted (per-block schema deferred
    // to 6.4.0).
    const target = join(OUTPUT_DIR, 'epics-context', 'epic-1-context.md');
    writeFileSync(join(sandbox, target), CONFORMANT_CACHE);
    const r = run(sandbox, target);
    expect(r.stderr).not.toMatch(/invented heading/);
    expect(r.code).toBe(0);
  });
});
